parameters:
#    tesla_ws.example.class: Tesla\Bundle\WsBundle\Example

     tesla_ws.reader_cache_path: %kernel.cache_dir%/tesla_annot_reader
services:
#    tesla_ws.example:
#        class: %tesla_ws.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    tesla_ws.vary_handler:
        class: Tesla\Bundle\WsBundle\Handlers\VaryHandler
        public: false

    tesla_ws.json_handler:
        class: Tesla\Bundle\WsBundle\Handlers\JsonHandler
        public: false


    tesla_ws.handler_activator:
        class: Tesla\Bundle\WsBundle\Listener\HandlerActivator
        public: false
        arguments:
            - %tesla_ws.reader_cache_path%
            - @annotation_reader
            - %KERNEL.ENVIRONMENT%
        calls:
            - [setLogger, [@logger]]
            # add handlers for annotation alias name
            - [addHandler, [tesla_ws_json, @tesla_ws.json_handler]]
            - [addHandler, [tesla_ws_vary, @tesla_ws.vary_handler]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, priority:-1 }
            - { name: kernel.event_listener, event: kernel.response, priority:-1 }
            - { name: kernel.event_listener, event: kernel.view, priority:-1 }
            - { name: kernel.event_listener, event: kernel.exception, priority:-1 }
