parameters:
#    tesla_ws.example.class: Tesla\Bundle\WsBundle\Example

     tesla_ws.reader_cache_path: %kernel.cache_dir%/tesla_annot_reader
services:
#    tesla_ws.example:
#        class: %tesla_ws.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
